//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pz_18
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentRequests
    {
        public int EquipmentRequestID { get; set; }
        public string ProblemDescription { get; set; }
        public int Status { get; set; }
        public int RequestID { get; set; }
        public int MasterID { get; set; }
        public int ManagerID { get; set; }
    
        public virtual Managers Managers { get; set; }
        public virtual Masters Masters { get; set; }
        public virtual Requests Requests { get; set; }
        public virtual StatusRequests StatusRequests { get; set; }
    }
}
