//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pz_18
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requests()
        {
            this.Comments = new HashSet<Comments>();
            this.EquipmentRequests = new HashSet<EquipmentRequests>();
        }
    
        public int RequestID { get; set; }
        public System.DateTime StartDate { get; set; }
        public int ModelID { get; set; }
        public string ProblemDescription { get; set; }
        public int StatusRequest { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string RepairParts { get; set; }
        public int MasterID { get; set; }
        public int ClientID { get; set; }
    
        public virtual Clients Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentRequests> EquipmentRequests { get; set; }
        public virtual HomeTechModel HomeTechModel { get; set; }
        public virtual Masters Masters { get; set; }
        public virtual StatusRequests StatusRequests { get; set; }
    }
}
