//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildingProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConstructionProjectEntities : DbContext
    {
        public static ConstructionProjectEntities _context;
        public ConstructionProjectEntities()
            : base("name=ConstructionProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
        }

        public static ConstructionProjectEntities GetContext()
        {
            if (_context == null)
                _context = new ConstructionProjectEntities();
            return _context;
        }
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<Providers> Providers { get; set; }
        public virtual DbSet<Supervisors> Supervisors { get; set; }
        public virtual DbSet<UnitOfMeasurement> UnitOfMeasurement { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Сategory> Сategory { get; set; }
    }
}
