//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildingProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materials()
        {
            this.Project = new HashSet<Project>();
        }
    
        public decimal ID_Material { get; set; }
        public string Nname { get; set; }
        public int UnitPrice { get; set; }
        public int QuantityStorage { get; set; }
        public decimal UnitOfMeasurement { get; set; }
        public decimal Сategory { get; set; }
        public decimal Providers { get; set; }
    
        public virtual Providers Providers1 { get; set; }
        public virtual UnitOfMeasurement UnitOfMeasurement1 { get; set; }
        public virtual Сategory Сategory1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project> Project { get; set; }
    }
}
