//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demm1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int ID { get; set; }
        public System.DateTime startDate { get; set; }
        public int carModelID { get; set; }
        public string problemDescryption { get; set; }
        public int requestStatusID { get; set; }
        public Nullable<System.DateTime> completionDate { get; set; }
        public string repairParts { get; set; }
        public Nullable<int> masterID { get; set; }
        public int clientID { get; set; }
    
        public virtual carModel carModel { get; set; }
        public virtual requestStatus requestStatus { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
